services:
  postgres:
    image: postgres:16.0
    container_name: calciumdb
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - service-api-calcium

  my-service-production:
    container_name: calciumapi-production-service
    env_file: .env
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - service-api-calcium

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    volumes:
      - .:/project
      - node_modules:/project/node_modules/

volumes:
  node_modules:

networks:
  service-api-calcium:
    external: true
